networks:
  charitychain-net:
    external: true

services:
  orderer.orderer.example.com:
    container_name: orderer.orderer.example.com
    image: hyperledger/fabric-orderer:2.5
    platform: linux/amd64 # Specify platform for consistency
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis-block/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ordererOrgMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1 # For solo orderer (though Kafka itself is not used in solo)
      - ORDERER_KAFKA_VERBOSE=true # For solo orderer
      # For Fabric 2.x, these cluster env vars are needed even for a single solo orderer
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block:/var/hyperledger/orderer/genesis-block
      - ../organizations/ordererOrg/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrg/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - charitychain-net
