Organizations:
  - &charityOrg
    Name: charityOrg
    ID: charityOrgMSP
    MSPDir: ../organizations/charityOrg/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('charityOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('charityOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('charityOrgMSP.admin')"
    AnchorPeers:
      - Host: peer0-charityOrg.charity.example.com
        Port: 7051
  - &donorOrg
    Name: donorOrg
    ID: donorOrgMSP
    MSPDir: ../organizations/donorOrg/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('donorOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('donorOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('donorOrgMSP.admin')"
    AnchorPeers:
      - Host: peer0-donorOrg.donor.example.com
        Port: 9051
  - &ordererOrg
    Name: ordererOrg
    ID: ordererOrgMSP
    MSPDir: ../organizations/ordererOrg/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordererOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordererOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordererOrgMSP.admin')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations: # To be specified in profile
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation: # Used by the orderer system channel
      Type: ImplicitMeta
      Rule: "ANY Writers" # Default policy
  Capabilities:
    <<: *OrdererCapabilities

Application: &ApplicationDefaults
  Organizations: 
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: Signature
      Rule: "OR('charityOrgMSP.member', 'donorOrgMSP.member')"
    Endorsement:
      Type: Signature
      Rule: "OR('charityOrgMSP.member', 'donorOrgMSP.member')"
  Capabilities:
    <<: *ApplicationCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *ordererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *charityOrg
          - *donorOrg
  TwoOrgsChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *charityOrg
        - *donorOrg
      Capabilities:
        <<: *ApplicationCapabilities
